// src/components/spinner/Spinner.tsx
import "./Spinner.css";

interface SpinnerProps {
	size?: string;
	label?: string;
	className?: string;
}

const Spinner = ({
	size = "md",
	label = "Loading...",
	className,
}: SpinnerProps) => {
	const classNames = `spinner spinner-${size}${className ? ` ${className}` : ""}`;
	return <div className={classNames} role="status" aria-label={label} />;
};

export default Spinner;

// packages/svelte/src/lib/components/spinner/Spinner.svelte
<script lang="ts">
interface Props {
	size?: string;
	label?: string;
	class?: string;
}

let { size = "md", label = "Loading...", class: className }: Props = $props();

let classNames = $derived(
	`spinner spinner-${size}${className ? ` ${className}` : ""}`,
);
</script>

<div class={classNames} role="status" aria-label={label}></div>
