// packages/svelte/src/lib/components/form-field/FormField.svelte
<script lang="ts">
import type { Snippet } from "svelte";

interface Props {
	children: Snippet;
	error?: string;
}

let { children, error }: Props = $props();

let errorClass = $derived(error ? "error" : null);
let classNames = $derived(`form-field ${errorClass}`);
</script>

<div class={classNames}>
	{@render children()}
	{#if error}
		<div class="error-message">{error}</div>
	{/if}
</div>

// src/components/form-field/FormField.jsx
import React from 'react';
import './FormField.scss';

const ErrorMessage = ({ error }) => (
	<div className="error-message">{error}</div>
);

const FormField = ({ children, error }) => {
	const errorClass = error ? 'error' : null;
	const errorMessage = error ? <ErrorMessage error={error} /> : null;
	const classNames = `form-field ${errorClass}`;
	return (
		<div className={classNames}>
			{children}
			{errorMessage}
		</div>
	);
};

export default FormField;
