// packages/svelte/src/lib/components/input/Input.svelte
<script lang="ts">
interface Props {
	type?: string;
	class?: string;
	defaultValue?: string;
	placeholder?: string;
	name?: string;
	onchange?: (event: Event) => void;
	ref?: HTMLInputElement | null;
}

let {
	type = "text",
	class: className,
	defaultValue,
	placeholder,
	name,
	onchange,
	ref = $bindable(null),
}: Props = $props();
</script>

<input
	bind:this={ref}
	{name}
	{type}
	class={className}
	value={defaultValue}
	{onchange}
	{placeholder}
/>

// src/components/input/Input.tsx
import { forwardRef } from "react";

interface InputProps {
	type?: string;
	className?: string;
	defaultValue?: string;
	placeholder?: string;
	name?: string;
	onChange?: React.ChangeEventHandler<HTMLInputElement>;
}

const Input = forwardRef<HTMLInputElement, InputProps>(function input(
	{ type = "text", className, defaultValue, placeholder, name, onChange },
	ref,
) {
	return (
		<input
			ref={ref}
			name={name}
			type={type}
			className={className}
			defaultValue={defaultValue}
			onChange={onChange}
			placeholder={placeholder}
		/>
	);
});

export default Input;
