// packages/react/src/components/code-editor/CodeEditor.tsx
import "@anephenix/ui-tokens/components/code/Code.css";
import "@anephenix/ui-tokens/components/code-editor/CodeEditor.css";
import copy from "clipboard-copy";
import { useEffect, useRef, useState } from "react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";

const DEFAULT_LANGUAGES = ["javascript", "jsx", "css"];
const MIN_WIDTH = 280;
const MIN_HEIGHT = 120;
const TAB_INSERT = "  ";

interface TitleBarButtonsProps {
	isFullscreen: boolean;
	onToggleFullscreen: () => void;
}

const TitleBarButtons = ({
	isFullscreen,
	onToggleFullscreen,
}: TitleBarButtonsProps) => (
	<div id="title-bar-buttons">
		<div className="title-bar-button" id="close" />
		<div className="title-bar-button" id="minimize" />
		<button
			type="button"
			className="title-bar-button title-bar-button-action"
			id="maximize"
			aria-label={isFullscreen ? "Exit fullscreen" : "Expand to fullscreen"}
			aria-pressed={isFullscreen}
			onClick={onToggleFullscreen}
		/>
	</div>
);

interface CodeEditorProps {
	title?: string;
	code?: string;
	language?: string;
	languages?: string[];
	width?: number;
	height?: number;
	resizable?: boolean;
	expandable?: boolean;
	onChange?: (code: string) => void;
	onFinishedTyping?: (code: string) => void;
	finishedTypingDelay?: number;
}

const CodeEditor = ({
	title,
	code: initialCode = "",
	language: initialLanguage = "javascript",
	languages = DEFAULT_LANGUAGES,
	width: initialWidth = 600,
	height: initialHeight = 300,
	resizable = true,
	expandable = true,
	onChange,
	onFinishedTyping,
	finishedTypingDelay = 800,
}: CodeEditorProps) => {
	const [code, setCode] = useState(initialCode);
	const [language, setLanguage] = useState(initialLanguage);
	const [width, setWidth] = useState(initialWidth);
	const [height, setHeight] = useState(initialHeight);
	const [isFullscreen, setIsFullscreen] = useState(false);
	const [cursorLine, setCursorLine] = useState(1);
	const [cursorColumn, setCursorColumn] = useState(1);

	const textareaRef = useRef<HTMLTextAreaElement>(null);
	const preWrapperRef = useRef<HTMLDivElement>(null);
	const lineNumbersRef = useRef<HTMLDivElement>(null);
	const finishedTypingTimer = useRef<ReturnType<typeof setTimeout> | null>(
		null,
	);
	const resizeStart = useRef<{
		x: number;
		y: number;
		width: number;
		height: number;
	} | null>(null);

	const lineNumbers = Array.from(
		{ length: code.split("\n").length },
		(_, i) => i + 1,
	);
	const languageOptions = languages.includes(language)
		? languages
		: [language, ...languages];

	const updateCursorPosition = (target: HTMLTextAreaElement) => {
		const upToCursor = target.value.slice(0, target.selectionStart ?? 0);
		const lines = upToCursor.split("\n");
		setCursorLine(lines.length);
		setCursorColumn(lines[lines.length - 1].length + 1);
	};

	const handleSelect = (event: React.SyntheticEvent<HTMLTextAreaElement>) => {
		updateCursorPosition(event.currentTarget);
	};

	const scheduleFinishedTyping = (value: string) => {
		if (!onFinishedTyping) return;
		if (finishedTypingTimer.current) clearTimeout(finishedTypingTimer.current);
		finishedTypingTimer.current = setTimeout(() => {
			onFinishedTyping(value);
		}, finishedTypingDelay);
	};

	useEffect(
		() => () => {
			if (finishedTypingTimer.current)
				clearTimeout(finishedTypingTimer.current);
		},
		[],
	);

	const syncScrollPositions = () => {
		const textarea = textareaRef.current;
		if (!textarea) return;
		const { scrollTop, scrollLeft } = textarea;
		if (preWrapperRef.current) {
			preWrapperRef.current.scrollTop = scrollTop;
			preWrapperRef.current.scrollLeft = scrollLeft;
		}
		if (lineNumbersRef.current) {
			lineNumbersRef.current.scrollTop = scrollTop;
		}
	};

	const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
		const value = event.target.value;
		setCode(value);
		onChange?.(value);
		scheduleFinishedTyping(value);
		updateCursorPosition(event.target);
		// The browser may auto-scroll the textarea to reveal the caret on a
		// new line before the line-number column has re-rendered to match —
		// re-sync once the DOM has caught up, so the two never visibly drift.
		requestAnimationFrame(syncScrollPositions);
	};

	const handleBlur = () => {
		if (finishedTypingTimer.current) {
			clearTimeout(finishedTypingTimer.current);
			finishedTypingTimer.current = null;
		}
		onFinishedTyping?.(code);
	};

	const handleScroll = () => {
		syncScrollPositions();
	};

	const handleKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
		if (event.key !== "Tab") return;
		event.preventDefault();
		const textarea = event.currentTarget;
		const { selectionStart, selectionEnd, value } = textarea;
		const next = `${value.slice(0, selectionStart)}${TAB_INSERT}${value.slice(selectionEnd)}`;
		setCode(next);
		onChange?.(next);
		scheduleFinishedTyping(next);
		const caret = selectionStart + TAB_INSERT.length;
		requestAnimationFrame(() => {
			textarea.selectionStart = textarea.selectionEnd = caret;
			updateCursorPosition(textarea);
			syncScrollPositions();
		});
	};

	const toggleFullscreen = () => {
		if (!expandable) return;
		setIsFullscreen((value) => !value);
	};

	useEffect(() => {
		if (!isFullscreen) return;
		const previousOverflow = document.body.style.overflow;
		document.body.style.overflow = "hidden";
		const onKeyDown = (event: KeyboardEvent) => {
			if (event.key === "Escape") setIsFullscreen(false);
		};
		window.addEventListener("keydown", onKeyDown);
		return () => {
			document.body.style.overflow = previousOverflow;
			window.removeEventListener("keydown", onKeyDown);
		};
	}, [isFullscreen]);

	const handleResizeStart = (event: React.MouseEvent) => {
		if (!resizable || isFullscreen) return;
		event.preventDefault();
		resizeStart.current = { x: event.clientX, y: event.clientY, width, height };

		const onMouseMove = (moveEvent: MouseEvent) => {
			if (!resizeStart.current) return;
			const deltaX = moveEvent.clientX - resizeStart.current.x;
			const deltaY = moveEvent.clientY - resizeStart.current.y;
			setWidth(Math.max(MIN_WIDTH, resizeStart.current.width + deltaX));
			setHeight(Math.max(MIN_HEIGHT, resizeStart.current.height + deltaY));
		};

		const onMouseUp = () => {
			resizeStart.current = null;
			window.removeEventListener("mousemove", onMouseMove);
			window.removeEventListener("mouseup", onMouseUp);
		};

		window.addEventListener("mousemove", onMouseMove);
		window.addEventListener("mouseup", onMouseUp);
	};

	return (
		<div
			className={`code code-editor-window${isFullscreen ? " is-fullscreen" : ""}`}
			style={isFullscreen ? undefined : { width }}
		>
			<div id="title-bar">
				<TitleBarButtons
					isFullscreen={isFullscreen}
					onToggleFullscreen={toggleFullscreen}
				/>
				<div id="title-bar-title">{title}</div>
				<div id="title-bar-actions">
					<button
						type="button"
						className="title-bar-action"
						onClick={() => copy(code)}
					>
						Copy
					</button>
				</div>
			</div>
			<div
				className="code-editor code-editor-body"
				style={{
					height: isFullscreen ? undefined : height,
					alignItems: "stretch",
					overflowY: "auto",
				}}
			>
				<div
					className="code-line-numbers"
					ref={lineNumbersRef}
					style={{ overflow: "hidden" }}
					aria-hidden="true"
				>
					{lineNumbers.map((n) => (
						<span key={n} className="code-line-number">
							{n}
						</span>
					))}
				</div>
				<div className="code-editor-surface">
					<div
						className="code-editor-pre-wrapper"
						ref={preWrapperRef}
						aria-hidden="true"
					>
						<SyntaxHighlighter
							language={language}
							style={oneDark}
							customStyle={{
								background: "transparent",
								margin: 0,
								padding: 0,
								fontSize: "10pt",
								borderRadius: 0,
								overflow: "visible",
							}}
						>
							{code}
						</SyntaxHighlighter>
					</div>
					<textarea
						ref={textareaRef}
						className="code-editor-textarea"
						value={code}
						onChange={handleChange}
						onScroll={handleScroll}
						onKeyDown={handleKeyDown}
						onKeyUp={handleSelect}
						onClick={handleSelect}
						onSelect={handleSelect}
						onBlur={handleBlur}
						spellCheck={false}
						autoCapitalize="off"
						autoCorrect="off"
						aria-label={title ? `${title} code editor` : "Code editor"}
					/>
				</div>
			</div>
			<div className="code-editor-footer">
				<select
					className="code-editor-language-select"
					value={language}
					onChange={(event) => setLanguage(event.target.value)}
					aria-label="Language"
				>
					{languageOptions.map((lang) => (
						<option key={lang} value={lang}>
							{lang}
						</option>
					))}
				</select>
				<span className="code-editor-position">
					Ln {cursorLine}, Col {cursorColumn}
				</span>
				{resizable && !isFullscreen && (
					<button
						type="button"
						className="code-editor-resize-handle"
						onMouseDown={handleResizeStart}
						aria-label="Resize editor"
					/>
				)}
			</div>
		</div>
	);
};

export default CodeEditor;

// packages/svelte/src/lib/components/code-editor/CodeEditor.svelte
<script lang="ts">
import "@anephenix/ui-tokens/components/code/Code.css";
import "@anephenix/ui-tokens/components/code-editor/CodeEditor.css";
import copy from "clipboard-copy";
import Prism from "prismjs";
// Only the languages actually used in this codebase are registered.
// Add another `import "prismjs/components/prism-x.js";` line here to
// support a new language — each file pulls in its own dependency
// chain (e.g. jsx registers markup, clike, and javascript too).
import "prismjs/components/prism-jsx.js";
import "prismjs/components/prism-css.js";

const DEFAULT_LANGUAGES = ["javascript", "jsx", "css"];
const MIN_WIDTH = 280;
const MIN_HEIGHT = 120;
const TAB_INSERT = "  ";

interface Props {
	title?: string;
	code?: string;
	language?: string;
	languages?: string[];
	width?: number;
	height?: number;
	resizable?: boolean;
	expandable?: boolean;
	onchange?: (code: string) => void;
	onfinishedtyping?: (code: string) => void;
	finishedTypingDelay?: number;
}

let {
	title,
	code = $bindable(""),
	language = $bindable("javascript"),
	languages = DEFAULT_LANGUAGES,
	width: initialWidth = 600,
	height: initialHeight = 300,
	resizable = true,
	expandable = true,
	onchange,
	onfinishedtyping,
	finishedTypingDelay = 800,
}: Props = $props();

// svelte-ignore state_referenced_locally -- initialWidth/initialHeight only
// seed the starting size, matching React's useState(initialWidth).
let width = $state(initialWidth);
// svelte-ignore state_referenced_locally
let height = $state(initialHeight);
let isFullscreen = $state(false);
let cursorLine = $state(1);
let cursorColumn = $state(1);

let textareaEl: HTMLTextAreaElement | null = $state(null);
let preWrapperEl: HTMLDivElement | null = $state(null);
let lineNumbersEl: HTMLDivElement | null = $state(null);
let finishedTypingTimer: ReturnType<typeof setTimeout> | null = null;
let resizeStart: {
	x: number;
	y: number;
	width: number;
	height: number;
} | null = null;

function escapeHtml(value: string): string {
	return value
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;");
}

let lineNumbers = $derived(
	Array.from({ length: code.split("\n").length }, (_, i) => i + 1),
);

let languageOptions = $derived(
	languages.includes(language) ? languages : [language, ...languages],
);

let highlighted = $derived.by(() => {
	const grammar = Prism.languages[language];
	return grammar ? Prism.highlight(code, grammar, language) : escapeHtml(code);
});

function updateCursorPosition(target: HTMLTextAreaElement) {
	const upToCursor = target.value.slice(0, target.selectionStart ?? 0);
	const lines = upToCursor.split("\n");
	cursorLine = lines.length;
	cursorColumn = lines[lines.length - 1].length + 1;
}

function handleSelect(event: Event) {
	updateCursorPosition(event.target as HTMLTextAreaElement);
}

function scheduleFinishedTyping(value: string) {
	if (!onfinishedtyping) return;
	if (finishedTypingTimer) clearTimeout(finishedTypingTimer);
	finishedTypingTimer = setTimeout(() => {
		onfinishedtyping(value);
	}, finishedTypingDelay);
}

$effect(() => {
	return () => {
		if (finishedTypingTimer) clearTimeout(finishedTypingTimer);
	};
});

function syncScrollPositions() {
	if (!textareaEl) return;
	const { scrollTop, scrollLeft } = textareaEl;
	if (preWrapperEl) {
		preWrapperEl.scrollTop = scrollTop;
		preWrapperEl.scrollLeft = scrollLeft;
	}
	if (lineNumbersEl) {
		lineNumbersEl.scrollTop = scrollTop;
	}
}

function handleInput(event: Event) {
	const value = (event.target as HTMLTextAreaElement).value;
	code = value;
	onchange?.(value);
	scheduleFinishedTyping(value);
	updateCursorPosition(event.target as HTMLTextAreaElement);
	// The browser may auto-scroll the textarea to reveal the caret on a new
	// line before the line-number column has re-rendered to match — re-sync
	// once the DOM has caught up, so the two never visibly drift.
	requestAnimationFrame(syncScrollPositions);
}

function handleBlur() {
	if (finishedTypingTimer) {
		clearTimeout(finishedTypingTimer);
		finishedTypingTimer = null;
	}
	onfinishedtyping?.(code);
}

function handleScroll() {
	syncScrollPositions();
}

function handleKeyDown(event: KeyboardEvent) {
	if (event.key !== "Tab") return;
	event.preventDefault();
	const textarea = event.currentTarget as HTMLTextAreaElement;
	const { selectionStart, selectionEnd, value } = textarea;
	const next = `${value.slice(0, selectionStart)}${TAB_INSERT}${value.slice(selectionEnd)}`;
	code = next;
	onchange?.(next);
	scheduleFinishedTyping(next);
	const caret = selectionStart + TAB_INSERT.length;
	requestAnimationFrame(() => {
		textarea.selectionStart = textarea.selectionEnd = caret;
		updateCursorPosition(textarea);
		syncScrollPositions();
	});
}

function toggleFullscreen() {
	if (!expandable) return;
	isFullscreen = !isFullscreen;
}

$effect(() => {
	if (!isFullscreen) return;
	const previousOverflow = document.body.style.overflow;
	document.body.style.overflow = "hidden";
	const onKeyDown = (event: KeyboardEvent) => {
		if (event.key === "Escape") isFullscreen = false;
	};
	window.addEventListener("keydown", onKeyDown);
	return () => {
		document.body.style.overflow = previousOverflow;
		window.removeEventListener("keydown", onKeyDown);
	};
});

function handleResizeStart(event: MouseEvent) {
	if (!resizable || isFullscreen) return;
	event.preventDefault();
	resizeStart = { x: event.clientX, y: event.clientY, width, height };

	const onMouseMove = (moveEvent: MouseEvent) => {
		if (!resizeStart) return;
		const deltaX = moveEvent.clientX - resizeStart.x;
		const deltaY = moveEvent.clientY - resizeStart.y;
		width = Math.max(MIN_WIDTH, resizeStart.width + deltaX);
		height = Math.max(MIN_HEIGHT, resizeStart.height + deltaY);
	};

	const onMouseUp = () => {
		resizeStart = null;
		window.removeEventListener("mousemove", onMouseMove);
		window.removeEventListener("mouseup", onMouseUp);
	};

	window.addEventListener("mousemove", onMouseMove);
	window.addEventListener("mouseup", onMouseUp);
}
</script>

<div
	class="code code-editor-window{isFullscreen ? ' is-fullscreen' : ''}"
	style={isFullscreen ? undefined : `width: ${width}px`}
>
	<div id="title-bar">
		<div id="title-bar-buttons">
			<div class="title-bar-button" id="close"></div>
			<div class="title-bar-button" id="minimize"></div>
			<button
				type="button"
				class="title-bar-button title-bar-button-action"
				id="maximize"
				aria-label={isFullscreen ? "Exit fullscreen" : "Expand to fullscreen"}
				aria-pressed={isFullscreen}
				onclick={toggleFullscreen}
			></button>
		</div>
		<div id="title-bar-title">{title}</div>
		<div id="title-bar-actions">
			<button type="button" class="title-bar-action" onclick={() => copy(code)}>
				Copy
			</button>
		</div>
	</div>
	<div
		class="code-editor code-editor-body"
		style="align-items: stretch; overflow-y: auto;{isFullscreen ? '' : ` height: ${height}px;`}"
	>
		<div
			class="code-line-numbers"
			bind:this={lineNumbersEl}
			style="overflow: hidden;"
			aria-hidden="true"
		>
			{#each lineNumbers as n (n)}
				<span class="code-line-number">{n}</span>
			{/each}
		</div>
		<div class="code-editor-surface">
			<div class="code-editor-pre-wrapper" bind:this={preWrapperEl} aria-hidden="true">
				<pre
					class="language-{language}"
					style="padding: 0; margin: 0; overflow: visible;"
				><code class="language-{language}">{@html highlighted}</code></pre>
			</div>
			<textarea
				bind:this={textareaEl}
				class="code-editor-textarea"
				value={code}
				oninput={handleInput}
				onscroll={handleScroll}
				onkeydown={handleKeyDown}
				onkeyup={handleSelect}
				onclick={handleSelect}
				onselect={handleSelect}
				onblur={handleBlur}
				spellcheck="false"
				autocapitalize="off"
				autocorrect="off"
				aria-label={title ? `${title} code editor` : "Code editor"}
			></textarea>
		</div>
	</div>
	<div class="code-editor-footer">
		<select
			class="code-editor-language-select"
			bind:value={language}
			aria-label="Language"
		>
			{#each languageOptions as lang (lang)}
				<option value={lang}>{lang}</option>
			{/each}
		</select>
		<span class="code-editor-position">Ln {cursorLine}, Col {cursorColumn}</span>
		{#if resizable && !isFullscreen}
			<button
				type="button"
				class="code-editor-resize-handle"
				onmousedown={handleResizeStart}
				aria-label="Resize editor"
			></button>
		{/if}
	</div>
</div>
