// packages/svelte/src/lib/components/textarea/Textarea.svelte
<script lang="ts">
interface Props {
	class?: string;
	defaultValue?: string;
	placeholder?: string;
	name?: string;
	onchange?: (event: Event) => void;
	ref?: HTMLTextAreaElement | null;
}

let {
	class: className,
	defaultValue,
	placeholder,
	name,
	onchange,
	ref = $bindable(null),
}: Props = $props();
</script>

<textarea
	bind:this={ref}
	{name}
	class={className}
	value={defaultValue}
	{onchange}
	{placeholder}
></textarea>

// src/components/textarea/Textarea.tsx
import { forwardRef } from "react";

interface TextareaProps {
	className?: string;
	defaultValue?: string;
	placeholder?: string;
	name?: string;
	onChange?: React.ChangeEventHandler<HTMLTextAreaElement>;
}

const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
	function textarea(
		{ className, defaultValue, placeholder, name, onChange },
		ref,
	) {
		return (
			<textarea
				ref={ref}
				name={name}
				className={className}
				defaultValue={defaultValue}
				onChange={onChange}
				placeholder={placeholder}
			/>
		);
	},
);

export default Textarea;
