// src/components/divider/Divider.jsx
import "./Divider.css";

const Divider = ({
	orientation = "horizontal",
	variant = "solid",
	label,
	className = "",
}) => {
	const classNames = `divider divider-${orientation} divider-${variant}${className ? ` ${className}` : ""}`;

	if (orientation === "horizontal" && !label) {
		return <hr className={classNames} />;
	}

	return (
		<div aria-hidden="true" className={classNames}>
			{label && <span className="divider-label">{label}</span>}
		</div>
	);
};

export default Divider;

// packages/svelte/src/lib/components/divider/Divider.svelte
<script lang="ts">
interface Props {
	orientation?: "horizontal" | "vertical";
	variant?: string;
	label?: string;
	class?: string;
}

let {
	orientation = "horizontal",
	variant = "solid",
	label,
	class: className = "",
}: Props = $props();

let classNames = $derived(
	`divider divider-${orientation} divider-${variant}${className ? ` ${className}` : ""}`,
);
</script>

{#if orientation === "horizontal" && !label}
	<hr class={classNames} />
{:else}
	<div aria-hidden="true" class={classNames}>
		{#if label}
			<span class="divider-label">{label}</span>
		{/if}
	</div>
{/if}
