// src/components/select/Select.tsx
import { forwardRef } from "react";
import "./Select.css";

interface SelectOption {
	value: string;
	label: string;
}

interface SelectProps {
	className?: string;
	defaultValue?: string;
	name?: string;
	onChange?: React.ChangeEventHandler<HTMLSelectElement>;
	options: SelectOption[];
}

const Option = ({ value, label }: SelectOption, index: number) => (
	<option key={index} value={value}>
		{label}
	</option>
);

const Select = forwardRef<HTMLSelectElement, SelectProps>(function select(
	{ className, defaultValue, name, onChange, options },
	ref,
) {
	return (
		<select
			ref={ref}
			name={name}
			className={`select ${className}`}
			defaultValue={defaultValue}
			onChange={onChange}
		>
			{options.map(Option)}
		</select>
	);
});

export default Select;

// packages/svelte/src/lib/components/select/Select.svelte
<script lang="ts">
interface SelectOption {
	value: string;
	label: string;
}

interface Props {
	class?: string;
	defaultValue?: string;
	name?: string;
	onchange?: (event: Event) => void;
	options: SelectOption[];
	ref?: HTMLSelectElement | null;
}

let {
	class: className,
	defaultValue,
	name,
	onchange,
	options,
	ref = $bindable(null),
}: Props = $props();
</script>

<select bind:this={ref} {name} class="select {className}" value={defaultValue} {onchange}>
	{#each options as { value, label } (value)}
		<option {value}>{label}</option>
	{/each}
</select>
