// packages/svelte/src/lib/components/alert/Alert.svelte
<script lang="ts">
import type { Snippet } from "svelte";

type AlertVariant = "info" | "success" | "error" | "warning";

const variantIcons: Record<AlertVariant, string> = {
	success: "✓",
	error: "✕",
	warning: "⚠",
	info: "ℹ",
};

interface Props {
	variant?: AlertVariant;
	title?: string;
	children: Snippet;
	onclose?: () => void;
	class?: string;
}

let {
	variant = "info",
	title,
	children,
	onclose,
	class: className,
}: Props = $props();

let role = $derived(
	variant === "error" || variant === "warning" ? "alert" : "status",
);
let classNames = $derived(
	`alert alert-${variant}${className ? ` ${className}` : ""}`,
);
</script>

<div class={classNames} {role}>
	<div class="alert-icon">{variantIcons[variant]}</div>
	<div class="alert-content">
		{#if title}
			<div class="alert-title">{title}</div>
		{/if}
		<div class="alert-body">{@render children()}</div>
	</div>
	{#if onclose}
		<button type="button" class="alert-close" onclick={onclose} aria-label="Dismiss">
			&times;
		</button>
	{/if}
</div>

// src/components/alert/Alert.tsx
import "./Alert.css";

type AlertVariant = "info" | "success" | "error" | "warning";

const variantIcons: Record<AlertVariant, string> = {
	success: "✓",
	error: "✕",
	warning: "⚠",
	info: "ℹ",
};

interface AlertProps {
	variant?: AlertVariant;
	title?: string;
	children: React.ReactNode;
	onClose?: () => void;
	className?: string;
}

const Alert = ({
	variant = "info",
	title,
	children,
	onClose,
	className,
}: AlertProps) => {
	const role =
		variant === "error" || variant === "warning" ? "alert" : "status";
	const classNames = `alert alert-${variant}${className ? ` ${className}` : ""}`;

	return (
		<div className={classNames} role={role}>
			<div className="alert-icon">{variantIcons[variant]}</div>
			<div className="alert-content">
				{title && <div className="alert-title">{title}</div>}
				<div className="alert-body">{children}</div>
			</div>
			{onClose && (
				<button
					type="button"
					className="alert-close"
					onClick={onClose}
					aria-label="Dismiss"
				>
					&times;
				</button>
			)}
		</div>
	);
};

export default Alert;
