// packages/svelte/src/lib/components/modal/Modal.svelte
<script lang="ts">
import type { Snippet } from "svelte";

interface Props {
	isOpen: boolean;
	onClose?: () => void;
	title?: string;
	children: Snippet;
	footer?: Snippet;
}

let { isOpen, onClose, title, children, footer }: Props = $props();

let dialogRef: HTMLDialogElement;

$effect(() => {
	if (!dialogRef) return;
	if (isOpen) {
		if (!dialogRef.open) dialogRef.showModal();
	} else {
		if (dialogRef.open) dialogRef.close();
	}
});

$effect(() => {
	if (!dialogRef) return;
	function handleCancel() {
		onClose?.();
	}
	dialogRef.addEventListener("cancel", handleCancel);
	return () => dialogRef.removeEventListener("cancel", handleCancel);
});

function handleBackdropClick(e: MouseEvent) {
	if (e.target === dialogRef) onClose?.();
}
</script>

<dialog bind:this={dialogRef} class="modal" onclick={handleBackdropClick}>
	<div class="modal-content">
		<div class="modal-header">
			<h2 class="modal-title">{title}</h2>
			<button type="button" class="modal-close" onclick={onClose} aria-label="Close">
				&times;
			</button>
		</div>
		<div class="modal-body">{@render children()}</div>
		{#if footer}
			<div class="modal-footer">{@render footer()}</div>
		{/if}
	</div>
</dialog>

// packages/react/src/components/modal/Modal.tsx
import { useEffect, useRef } from "react";
import "@anephenix/ui-tokens/components/modal/Modal.css";

interface ModalProps {
	isOpen: boolean;
	onClose?: () => void;
	title?: string;
	children: React.ReactNode;
	footer?: React.ReactNode;
}

const Modal = ({ isOpen, onClose, title, children, footer }: ModalProps) => {
	const dialogRef = useRef<HTMLDialogElement>(null);

	useEffect(() => {
		const dialog = dialogRef.current;
		if (!dialog) return;
		if (isOpen) {
			if (!dialog.open) dialog.showModal();
		} else {
			if (dialog.open) dialog.close();
		}
	}, [isOpen]);

	useEffect(() => {
		const dialog = dialogRef.current;
		if (!dialog) return;
		const handleCancel = () => onClose?.();
		dialog.addEventListener("cancel", handleCancel);
		return () => dialog.removeEventListener("cancel", handleCancel);
	}, [onClose]);

	const handleBackdropClick = (e: React.MouseEvent<HTMLDialogElement>) => {
		if (e.target === dialogRef.current) onClose?.();
	};

	return (
		// biome-ignore lint/a11y/useKeyWithClickEvents: <dialog> handles keyboard interaction natively via the cancel event (Escape key)
		<dialog ref={dialogRef} className="modal" onClick={handleBackdropClick}>
			<div className="modal-content">
				<div className="modal-header">
					<h2 className="modal-title">{title}</h2>
					<button
						type="button"
						className="modal-close"
						onClick={onClose}
						aria-label="Close"
					>
						&times;
					</button>
				</div>
				<div className="modal-body">{children}</div>
				{footer && <div className="modal-footer">{footer}</div>}
			</div>
		</dialog>
	);
};

export default Modal;
