// src/components/form-field/FormField.tsx
import "./FormField.css";

interface ErrorMessageProps {
	error: string;
}

const ErrorMessage = ({ error }: ErrorMessageProps) => (
	<div className="error-message">{error}</div>
);

interface FormFieldProps {
	children: React.ReactNode;
	error?: string;
}

const FormField = ({ children, error }: FormFieldProps) => {
	const errorClass = error ? "error" : null;
	const errorMessage = error ? <ErrorMessage error={error} /> : null;
	const classNames = `form-field ${errorClass}`;
	return (
		<div className={classNames}>
			{children}
			{errorMessage}
		</div>
	);
};

export default FormField;

// packages/svelte/src/lib/components/form-field/FormField.svelte
<script lang="ts">
import type { Snippet } from "svelte";

interface Props {
	children: Snippet;
	error?: string;
}

let { children, error }: Props = $props();

let errorClass = $derived(error ? "error" : null);
let classNames = $derived(`form-field ${errorClass}`);
</script>

<div class={classNames}>
	{@render children()}
	{#if error}
		<div class="error-message">{error}</div>
	{/if}
</div>
