// packages/react/src/components/button/Button.tsx
import { forwardRef } from "react";

interface ButtonProps {
	className?: string;
	text?: string;
	name?: string;
	onClick?: React.MouseEventHandler<HTMLButtonElement>;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(function button(
	{ className, text, name, onClick },
	ref,
) {
	return (
		<button
			type="button"
			name={name}
			ref={ref}
			className={className}
			onClick={onClick}
		>
			{text}
		</button>
	);
});

export default Button;

// packages/svelte/src/lib/components/button/Button.svelte
<script lang="ts">
interface Props {
	class?: string;
	text?: string;
	name?: string;
	onclick?: (event: MouseEvent) => void;
	ref?: HTMLButtonElement | null;
}

let {
	class: className,
	text,
	name,
	onclick,
	ref = $bindable(null),
}: Props = $props();
</script>

<button type="button" {name} bind:this={ref} class={className} {onclick}>
	{text}
</button>
