// packages/svelte/src/lib/components/checkbox/Checkbox.svelte
<script lang="ts">
interface Props {
	label?: string;
	class?: string;
	name?: string;
	defaultValue?: boolean;
	ref?: HTMLInputElement | null;
}

let {
	label,
	class: className,
	name,
	defaultValue,
	ref = $bindable(null),
}: Props = $props();

let classNames = $derived(`checkbox ${className}`);
</script>

<label class={classNames}>
	<input type="checkbox" {name} bind:this={ref} checked={defaultValue} />
	<div class="checkbox-element">
		<div class="tick"></div>
	</div>
	<span>{label}</span>
</label>

// src/components/checkbox/Checkbox.tsx
import { forwardRef } from "react";

interface CheckboxProps {
	label?: string;
	className?: string;
	name?: string;
	defaultValue?: boolean;
}

const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function checkbox(
	{ label, className, name, defaultValue },
	ref,
) {
	const classNames = `checkbox ${className}`;
	return (
		<label className={classNames}>
			<input
				type="checkbox"
				name={name}
				ref={ref}
				defaultChecked={defaultValue}
			/>
			<div className="checkbox-element">
				<div className="tick"></div>
			</div>
			<span>{label}</span>
		</label>
	);
});

export default Checkbox;
