// packages/svelte/src/lib/components/footer/Footer.svelte
<script lang="ts">
import type { Snippet } from "svelte";

interface Props {
	leftSection?: Snippet;
	rightSection?: Snippet;
}

let { leftSection, rightSection }: Props = $props();
</script>

<div id="footer">
	<div class="container">
		<div class="withSidePadding">
			{#if leftSection}{@render leftSection()}{/if}
			{#if rightSection}{@render rightSection()}{/if}
		</div>
	</div>
</div>

// src/components/footer/Footer.jsx
import React from 'react';
// Components

// Styling
import './Footer.scss';

const Footer = ({leftSection, rightSection }) => (
	<div id="footer">
		<div className='container'>
			<div className='withSidePadding'>
				{leftSection}
				{rightSection}
			</div>
		</div>
	</div>
);

export default Footer;
