// packages/svelte/src/lib/components/footer/Footer.svelte
<script lang="ts">
import type { Snippet } from "svelte";

interface Props {
	leftSection?: Snippet;
	rightSection?: Snippet;
}

let { leftSection, rightSection }: Props = $props();
</script>

<div id="footer">
	<div class="container">
		<div class="withSidePadding">
			{#if leftSection}{@render leftSection()}{/if}
			{#if rightSection}{@render rightSection()}{/if}
		</div>
	</div>
</div>

// src/components/footer/Footer.tsx
import "./Footer.css";

interface FooterProps {
	leftSection?: React.ReactNode;
	rightSection?: React.ReactNode;
}

const Footer = ({ leftSection, rightSection }: FooterProps) => (
	<div id="footer">
		<div className="container">
			<div className="withSidePadding">
				{leftSection}
				{rightSection}
			</div>
		</div>
	</div>
);

export default Footer;
