// src/components/textarea/Textarea.jsx
import { forwardRef } from "react";

const Textarea = forwardRef(function textarea(
	{ className, defaultValue, placeholder, name, onChange },
	ref,
) {
	return (
		<textarea
			ref={ref}
			name={name}
			className={className}
			defaultValue={defaultValue}
			onChange={onChange}
			placeholder={placeholder}
		/>
	);
});

export default Textarea;

// packages/svelte/src/lib/components/textarea/Textarea.svelte
<script lang="ts">
interface Props {
	class?: string;
	defaultValue?: string;
	placeholder?: string;
	name?: string;
	onchange?: (event: Event) => void;
	ref?: HTMLTextAreaElement | null;
}

let {
	class: className,
	defaultValue,
	placeholder,
	name,
	onchange,
	ref = $bindable(null),
}: Props = $props();
</script>

<textarea
	bind:this={ref}
	{name}
	class={className}
	value={defaultValue}
	{onchange}
	{placeholder}
></textarea>
